// Maps a destination country name (as used in app/page.js's country lists)
// to the slug GOV.UK uses for FCDO foreign travel advice pages —
// https://www.gov.uk/foreign-travel-advice/{slug}. Most slugs are just the
// lowercased name, but a handful (Czechia, Bosnia and Herzegovina, USA
// territories, etc.) differ, so this is listed explicitly rather than
// derived at runtime. Verified against the live index at
// https://www.gov.uk/api/content/foreign-travel-advice.
//
// `null` means FCDO doesn't publish a page for it (the UK itself).
export const COUNTRY_TO_FCDO_SLUG = {
  // Europe
  "Albania": "albania",
  "Andorra": "andorra",
  "Austria": "austria",
  "Belgium": "belgium",
  "Bosnia & Herzegovina": "bosnia-and-herzegovina",
  "Bulgaria": "bulgaria",
  "Croatia": "croatia",
  "Cyprus": "cyprus",
  "Czech Republic": "czechia",
  "Denmark": "denmark",
  "Estonia": "estonia",
  "Finland": "finland",
  "France": "france",
  "Germany": "germany",
  "Greece": "greece",
  "Hungary": "hungary",
  "Iceland": "iceland",
  "Ireland": "ireland",
  "Italy": "italy",
  "Kosovo": "kosovo",
  "Latvia": "latvia",
  "Lithuania": "lithuania",
  "Luxembourg": "luxembourg",
  "Malta": "malta",
  "Moldova": "moldova",
  "Montenegro": "montenegro",
  "Netherlands": "netherlands",
  "North Macedonia": "north-macedonia",
  "Norway": "norway",
  "Poland": "poland",
  "Portugal": "portugal",
  "Romania": "romania",
  "Serbia": "serbia",
  "Slovakia": "slovakia",
  "Slovenia": "slovenia",
  "Spain": "spain",
  "Sweden": "sweden",
  "Switzerland": "switzerland",
  "Turkey": "turkey",
  "Ukraine": "ukraine",
  "United Kingdom": null,

  // Asia
  "Armenia": "armenia",
  "Azerbaijan": "azerbaijan",
  "Bahrain": "bahrain",
  "Bangladesh": "bangladesh",
  "Bhutan": "bhutan",
  "Brunei": "brunei",
  "Cambodia": "cambodia",
  "China": "china",
  "Georgia": "georgia",
  "Hong Kong": "hong-kong",
  "India": "india",
  "Indonesia": "indonesia",
  "Japan": "japan",
  "Jordan": "jordan",
  "Kazakhstan": "kazakhstan",
  "Kyrgyzstan": "kyrgyzstan",
  "Laos": "laos",
  "Lebanon": "lebanon",
  "Malaysia": "malaysia",
  "Maldives": "maldives",
  "Mongolia": "mongolia",
  "Myanmar": "myanmar",
  "Nepal": "nepal",
  "Oman": "oman",
  "Pakistan": "pakistan",
  "Philippines": "philippines",
  "Qatar": "qatar",
  "Saudi Arabia": "saudi-arabia",
  "Singapore": "singapore",
  "South Korea": "south-korea",
  "Sri Lanka": "sri-lanka",
  "Taiwan": "taiwan",
  "Tajikistan": "tajikistan",
  "Thailand": "thailand",
  "UAE": "united-arab-emirates",
  "Uzbekistan": "uzbekistan",
  "Vietnam": "vietnam",

  // Africa
  "Algeria": "algeria",
  "Angola": "angola",
  "Benin": "benin",
  "Botswana": "botswana",
  "Cameroon": "cameroon",
  "Cape Verde": "cape-verde",
  "Egypt": "egypt",
  "Ethiopia": "ethiopia",
  "Ghana": "ghana",
  "Kenya": "kenya",
  "Madagascar": "madagascar",
  "Malawi": "malawi",
  "Morocco": "morocco",
  "Mozambique": "mozambique",
  "Namibia": "namibia",
  "Nigeria": "nigeria",
  "Rwanda": "rwanda",
  "Senegal": "senegal",
  "Seychelles": "seychelles",
  "South Africa": "south-africa",
  "Tanzania": "tanzania",
  "Tunisia": "tunisia",
  "Uganda": "uganda",
  "Zambia": "zambia",
  "Zimbabwe": "zimbabwe",

  // North America
  "Bahamas": "bahamas",
  "Barbados": "barbados",
  "Canada": "canada",
  "Cuba": "cuba",
  "Dominican Republic": "dominican-republic",
  "Haiti": "haiti",
  "Jamaica": "jamaica",
  "Mexico": "mexico",
  "Puerto Rico": "usa", // FCDO covers it under the USA page
  "Trinidad & Tobago": "trinidad-and-tobago",
  "USA": "usa",

  // Central America
  "Belize": "belize",
  "Costa Rica": "costa-rica",
  "El Salvador": "el-salvador",
  "Guatemala": "guatemala",
  "Honduras": "honduras",
  "Nicaragua": "nicaragua",
  "Panama": "panama",

  // South America
  "Argentina": "argentina",
  "Bolivia": "bolivia",
  "Brazil": "brazil",
  "Chile": "chile",
  "Colombia": "colombia",
  "Ecuador": "ecuador",
  "Paraguay": "paraguay",
  "Peru": "peru",
  "Suriname": "suriname",
  "Uruguay": "uruguay",
  "Venezuela": "venezuela",

  // Oceania
  "Australia": "australia",
  "Cook Islands": "cook-islands-tokelau-and-niue",
  "Fiji": "fiji",
  "French Polynesia": "french-polynesia",
  "New Caledonia": "new-caledonia",
  "New Zealand": "new-zealand",
  "Papua New Guinea": "papua-new-guinea",
  "Samoa": "samoa",
  "Solomon Islands": "solomon-islands",
  "Tonga": "tonga",
  "Vanuatu": "vanuatu",

  // Middle East (Bahrain, Jordan, Lebanon, Oman, Qatar, Saudi Arabia, UAE
  // already listed above under Asia)
  "Iran": "iran",
  "Iraq": "iraq",
  "Israel": "israel",
  "Kuwait": "kuwait",
  "Yemen": "yemen",
};
